### ISSUE TITLE
【Suggestion】repair the error of "Undefined control sequence \colorbox" in compiling text_attention.tex 

### ISSUE THREAD

**Issue by xiamenwcy** [MLNLP-World/Paper-Picture-Writing-Code#1]
![image](https://user-images.githubusercontent.com/10195097/197370101-070ea4af-125c-4383-a5d8-81effe3789e2.png)

当出现以上错误时，

可以添加额外的包：

\documentclass{article}

**\usepackage{xcolor}**

**\usepackage{tcolorbox}**

\usepackage[utf8]{inputenc}

**Comment by qinlibo-hit** [comment]
@xiamenwcy Thank you very much for your kind suggestions:)
